import type { Metadata } from "next";
import "./globals.css";
import { Inter } from "next/font/google";
import clsx from "clsx";
import { Layout } from "@/components/shared/layout/Layout";

export const metadata: Metadata = {
  title: "123-Scraper",
  description: "Generated by create next app",
};

const inter = Inter({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-inter",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={clsx("antialiased", inter.className)}>
        <Layout>{children}</Layout>
      </body>
    </html>
  );
}
